name: Deploy to Server

on:
  push:
    branches:
      - main  # A fő branch neve, amelyről deploy-olsz

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_DOMAIN }} >> ~/.ssh/known_hosts

    - name: Add SSH Key with Passphrase
      run: |
        # Start the SSH agent
        eval $(ssh-agent -s)

        # Save private key to a file
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

        # Add the private key to the SSH agent
        echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add private_key.pem

        # Clean up private key file
        rm private_key.pem

    - name: Deploy files to server
      run: |
        scp -P ${{ secrets.SSH_PORT }} -r ./ public_html/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_DOMAIN }}:/home/${{ secrets.SSH_USER }}/public_html/

    - name: Clean up SSH
      run: |
        ssh-add -D
