name: Deploy to Server

on:
  workflow_dispatch:  # Manuális indítás
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up ssh
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_DOMAIN }} >> ~/.ssh/known_hosts

    - name: Start SSH Agent
      run: |
        eval $(ssh-agent -s)
        echo "SSH_AGENT_PID: $SSH_AGENT_PID"
        echo "SSH_AUTH_SOCK: $SSH_AUTH_SOCK"

    - name: Debug SSH Agent
      run: |
        echo "SSH_AGENT_PID: $SSH_AGENT_PID"
        echo "SSH_AUTH_SOCK: $SSH_AUTH_SOCK"
        ps -ef | grep ssh-agent
        ls -l $SSH_AUTH_SOCK

    - name: Add SSH Key
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key.pem
        chmod 600 private_key.pem
        ssh-add private_key.pem
        rm private_key.pem
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_AUTH_SOCK: $SSH_AUTH_SOCK

    - name: Deploy files to server
      run: |
        scp -P ${{ secrets.SSH_PORT }} -r ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_DOMAIN }}:/home/${{ secrets.SSH_USER }}/public_html/

    - name: Clean up SSH
      run: |
        ssh-add -D

