name: SSH Deploy

name: Deploy to Server

on:
  push:
    branches:
      - main  # vagy a fő branch neved

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy files to server
      run: |
        scp -r ./${{ secrets.SSH_USER }}@${{ secrets.SSH_DOMAIN }}.com:/home/username/public_html/
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clean up SSH
      run: |
        ssh-add -D
