name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_DOMAIN }} >> ~/.ssh/known_hosts
      env:
        SSH_DOMAIN: ${{ secrets.SSH_DOMAIN }}

    - name: Add SSH Key with Passphrase
      run: |
        eval $(ssh-agent -s)
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add private_key.pem
        rm private_key.pem

    - name: Deploy files to server
      run: |
        scp -P ${{ secrets.SSH_PORT }} -r ./ public_html/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_DOMAIN }}:/home/${{ secrets.SSH_USER }}/public_html/

    - name: Clean up SSH
      run: |
        ssh-add -D
