name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true  # Debug engedélyezése az egész jobban

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_DOMAIN }} >> ~/.ssh/known_hosts
      env:
        SSH_DOMAIN: ${{ secrets.SSH_DOMAIN }}
        SSH_PORT: ${{ secrets.SSH_PORT }}

    - name: Setup SSH agent and add private key
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key.pem
        chmod 600 private_key.pem
        ssh-add private_key.pem
        ssh-add -l
        rm private_key.pem
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

    - name: Test SSH Connection and Print Message
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_DOMAIN }} 'echo "Deploy sikeres!"'
      env:
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_DOMAIN: ${{ secrets.SSH_DOMAIN }}
